---
include:
  - "**/*.rb"
exclude:
  - ".bundle/**/*"
  - gem/dependencies/**/*
require: []
domains: []
reporters:
  - rubocop
  - require_not_found
plugins:
  - runtime
require_paths: []
max_files: 10000
