# frozen_string_literal: true

source 'https://rubygems.org'

ruby '2.5.1'

gem 'debase', require: false
gem 'ruby-debug-ide', require: false

gem "mry", require: false
gem "rubocop", "~> 0.70.0", require: false
gem "rubocop-performance", "~> 1.3.0", require: false
gem "rubocop-rails", require: false
gem "rubocop-github", "~> 0.13.0", require: false

gem "solargraph", require: false
