source 'https://rubygems.org'

ruby '2.5.1'

gem 'debase', '~> 0.2.2', require: false
gem 'rubocop', '~> 0.68.0', require: false
gem 'rubocop-performance', require: false
gem 'ruby-debug-ide', '~> 0.6.0', require: false
gem 'solargraph', '~> 0.32.2', require: false
 
